# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: Tu Thang Phat
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget
from PyQt5.QtCore import Qt, QTimer

class Ui_Ui_main(QMainWindow):
    def setupUi(self, Ui_main):
        Ui_main.setObjectName("Ui_main")
        Ui_main.resize(802, 523)
        Ui_main.setWindowFlags(Qt.FramelessWindowHint)
        Ui_main.setAttribute(Qt.WA_TranslucentBackground)
        Ui_main.setStyleSheet("backgroud: qlineargradient(rgba(0,0,0,0.9),rgba(0,0,0,0.9));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Ui_main)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame.setStyleSheet("border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(230, 61, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border-style: none;\n"
"color: white;\n"
"background: transparent;\n"
"align-items: center;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, -1, 731, 31))
        self.label_2.setStyleSheet("background-color:  rgb(32, 112, 151);\n"
"color: white;\n"
"border-radius: 5px;")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 0, 731, 501))
        self.label.setStyleSheet("border-radius: 10px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo-1531147646552-1eec68116469.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(240, 121, 351, 8))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 8))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255));\n"
"border-radius: 2px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 51, 741, 451))
        self.label_4.setStyleSheet("background: rgb(2, 49, 49, .2)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 41, 501))
        self.frame_2.setStyleSheet("background-color: rgb(4, 33, 47);\n"
"border-radius: 0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 2, 41, 41))
        self.pushButton.setStyleSheet("background-color: rgb(2, 16, 23);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(47, 47))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 60, 41, 31))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("unnamed (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(50, 30, 731, 21))
        self.frame_3.setStyleSheet("background-color: rgb(8, 65, 94);\n"
"border-radius: 0px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toolButton = QtWidgets.QToolButton(self.frame_3)
        self.toolButton.setGeometry(QtCore.QRect(3, 2, 25, 19))
        self.toolButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("51ZF+mT3QZL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setIconSize(QtCore.QSize(18, 18))
        self.toolButton.setObjectName("toolButton")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(772, 51, 9, 429))
        self.verticalScrollBar.setStyleSheet("QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"            border: 0px solid #999999;\n"
"            background: rgb(0, 13, 26,.5);\n"
"            width:10px;    \n"
"            margin: 0px 0px 0px 0px;\n"
"            border-radius: 4px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 0px;\n"
"              border: 0px solid red;\n"
"            border-radius: 4px;\n"
"            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(637, 3, 41, 23))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 1, 255), stop:1 rgba(219, 169, 42, 255));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(685, 3, 41, 23))
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(174, 255, 0, 255), stop:1 rgba(72, 145, 26, 255));")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3.clicked.connect(lambda: Ui_main.showMinimized())
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(734, 3, 41, 23))
        self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 103, 1, 255), stop:1 rgba(255, 205, 5, 255));")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(lambda: Ui_main.close())
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 3, 41, 23))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(174, 255, 0, 255), stop:1 rgba(72, 145, 26, 255));")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(9, 477, 771, 22))
        self.frame_4.setStyleSheet("background: rgb(0, 13, 26,.9);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(290, 160, 250, 250))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(342, 340, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.textBrowser.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.frame_4.raise_()
        self.verticalScrollBar.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Ui_main)
        QtCore.QMetaObject.connectSlotsByName(Ui_main)

    def retranslateUi(self, Ui_main):
        _translate = QtCore.QCoreApplication.translate
        Ui_main.setWindowTitle(_translate("Ui_main", "Ui_main"))
        self.textBrowser.setHtml(_translate("Ui_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Corbel Light\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">WEATHER TODAY</span></p></body></html>"))
        self.label_2.setText(_translate("Ui_main", "  Pycos Weather"))
        self.pushButton_3.setText(_translate("Ui_main", "-"))
        self.pushButton_4.setText(_translate("Ui_main", "O"))
        self.pushButton_5.setText(_translate("Ui_main", "X"))
        self.pushButton_6.setText(_translate("Ui_main", "><"))
        self.label_5.setText(_translate("Ui_main", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt;\">30</span><span style=\" font-size:72pt; vertical-align:super;\">o</span><span style=\" font-size:72pt;\">C</span></p></body></html>"))
        self.label_6.setText(_translate("Ui_main", "<html><head/><body><p><span style=\" font-size:12pt;\">Da Nang, Viet Nam</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_main = QtWidgets.QWidget()
    ui = Ui_Ui_main()
    ui.setupUi(Ui_main)
    Ui_main.show()
    sys.exit(app.exec_())
